products = [
    {
        '_id': '1',
        'name': 'Air Jordan 3 SE "Canvas"',
        'image': '/images/air_jordan_three_se_canvas.jpg',
        'description':
        'As its moniker suggests, the latest take on Tinker Hatfield\'s first-ever design for Michael Jordan\'s signature sneaker line is constructed with durable canvas. A light beige "Muslin" color takes over most of the upper, while supporting components along the tongue, at the spine and around the lower heel opt for a deeper yellow that introduces an "aged" look.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 200.99,
        'countInStock': 30,
        'size': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Air Jordan 8 "Rui Hachimura"',
        'image': '/images/air_jordan_eight_rui_hachimura.jpg',
        'description':
        'A mix of perforated and non-perforated suede combines with smooth synthetic leather throughout the upper, with overlays across the profiles and along the tongue boasting an "age" pattern. Hachimura\'s logo replaces Jumpman branding on the top of the tongue, although chenille material reprises its role; both components opt for a bold scarlet tone that nods to a number of the forward\'s personal touch points. Elsewhere, the sneaker\'s packaging is reworked for the special occasion, with tissue paper donning the aforementioned logo alongside NIKE, Inc. branding. The box itself deviates from the standard graphics in favor of one that depicts Hachimura winning the ball from two spirit hoopers; Japanese characters accompanying the image of the Washington Wizard, depicted as wearing the special Jordan 8.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 225.99,
        'countInStock': 50,
        'size': 8,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Air Jordan 1 High "Georgetown"',
        'image': '/images/air_jordan_one_high_eightyfive_georgetown.jpg',
        'description':
        'The upper features the premium flat leather the aforementioned Georgetown colors perfectly married with the classic color-blocking style, while a nylon tongue features a slight yellow tint hinting at the spongy interior padding. The interior lining and insoles are matching with the college grey, while the midsole is clean cut with white. The Air Jordan 1 Hi \'85 "Georgetown" also comes with a folded card detailing the technical design specs of the shoe, while an OG-style shoebox is likely part of the set.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 200.99,
        'countInStock': 15,
        'size': 7,
        'rating': 4.7,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'DIOR x Air Jordan 1 High',
        'image': '/images/dior_x_air_jordan_one_high.jpg',
        'description':
        'Jordan Brand connected with Parisian fashion house Dior to create history with the Jordan 1 Retro High Dior. This is the first time that Jordan has collaborated with a legacy fashion label like Dior, making this release one for the books. This release was limited to only 8,500 pairs, each pair individually numbered. This Jordan 1 Retro High is composed of a white and grey leather upper with traditional Dior monogram print Swoosh. These shoes are made in Italy with premium materials. Co-branded icy translucent soles, Dior branded tongue and Wings logo, and a silver "Air Dior" hang tag completes the design.',
        'brand': 'Dior',
        'category': 'Sneakers',
        'price': 7000.99,
        'size': 7,
        'countInStock': 7,
        'rating': 5.0,
        'numReviews': 5,
    },
    {
        '_id': '5',
        'name': 'Yeezy 350 Boost V2 "Blue Tint"',
        'image': '/images/yeezy_threehundredfifty_boost_vtwo_blue_tint.jpg',
        'description':
        'In a similar pattern to the renowned adidas Yeezy Boost 350 V2 Zebra, the adidas Yeezy Boost 350 V2 Blue Tint features a marbled grey Primeknit upper with a light grey side stripe that is decorated with bright red SPLY-350 text. At the base, a Blue Tint semi-translucent Boost sole adds cushioning and support.',
        'brand': 'Adidas Yeezy',
        'category': 'Sneakers',
        'price': 230.99,
        'countInStock': 50,
        'size': 12,
        'rating': 4.7,
        'numReviews': 12,
    },
    {
        '_id': '6',
        'name': 'Yeezy 350 Boost V2 "Oreo"',
        'image': '/images/yeezy_threehundredfifty_boost_vtwo_oreo.jpg',
        'description':
        'Yeezy adds another colorway of its most well-known design with the adidas Yeezy 350 Oreo. This 350 V2 dons a similar pattern as the Yecheil colorway, only this time ditching vibrant accents for a black and grey palette.This Yeezy 350 V2 is composed of a Oreo Primeknit upper with a dark tonal side stripe. A translucent Boost cushioned sole and grey interior completes the design.',
        'brand': 'Adidas Yeezy',
        'category': 'Sneakers',
        'price': 230.99,
        'countInStock': 70,
        'size': 10,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '7',
        'name': 'Nike Dunk Low "Cider"',
        'image': '/images/nike_dunk_low_cider.jpg',
        'description':
        'Dressed in a Off Noir, Cider, Dark Chocolate, and Wild Berry color scheme. This Nike Dunk Low comes constructed in a mix premium suede and leather materials highlighted with Berry accents on the branded tongues and heels. A Noir midsole atop a Chocolate Brown rubber outsole completes the design.',
        'brand': 'Nike',
        'category': 'Sneakers',
        'price': 210.99,
        'countInStock': 50,
        'size': 9,
        'rating': 3.0,
        'numReviews': 12,
    },
    {
        '_id': '8',
        'name': 'Nike MAG Back to the Future (2016)',
        'image': '/images/nike_mag_back_to_the_future.jpg',
        'description':
        'The Nike Mag is a fictional sneaker that was first seen in the 1989 film Back To The Future II. Worn by Marty McFly in a hypothetical 2015, the Nike Mag was designed by Tinker Hatfield for Universal Studios and has since been a figment of the imaginations of both sneakerheads and BTTF fanatics. In 2011, Nike released the Nike Mag 2011, but without self-lacing capabilities. On October 4th, 2016, the fully functional power-lacing Nike Mag was unveiled.',
        'brand': 'Nike',
        'category': 'Sneakers',
        'price': 99999.99,
        'countInStock': 5,
        'size': 8,
        'rating': 5.0,
        'numReviews': 10,
    },
    {
        '_id': '9',
        'name': 'Fendi Leather Mid Top',
        'image': '/images/fendi_leather_mid_top.jpg',
        'description':
        'Lace-up sneakers made from white leather. Inserts in tech mesh on the toe and jacquard FF fabric on the side. Rubber sole. Made in Italy.',
        'brand': 'Fendi',
        'category': 'Sneakers',
        'price': 1000.99,
        'countInStock': 19,
        'size': 8,
        'rating': 4.0,
        'numReviews': 10,
    },
    {
        '_id': '10',
        'name': 'Chanel Low Top Trainer',
        'image': '/images/chanel_low_top_trainer.jpg',
        'description':
        'Authentic Chanel Low Top Trainer. Made in France.',
        'brand': 'Chanel',
        'category': 'Sneakers',
        'price': 2199.99,
        'size': 7,
        'countInStock': 0,
        'rating': 4.3,
        'numReviews': 7,
    },
    {
        '_id': '11',
        'name': 'Yeezy Slide "Ochre"',
        'image': '/images/yeezy_slide_ochre.jpg',
        'description':
        'The adidas Yeezy Slide Ochre is constructed entirely of EVA foam in a monochromatic fashion. A soft footbed offers immediate step-in comfort for daily wear. From there, deep groove treads on the sole provide traction and support.',
        'brand': 'Adidas Yeezy',
        'category': 'Slides',
        'price': 70.99,
        'countInStock': 10,
        'size': 8,
        'rating': 4.7,
        'numReviews': 30,
    },
    {
        '_id': '12',
        'name': 'Gucci GG Slide',
        'image': '/images/gucci_gg_slide.jpg',
        'description':
        'The slide sandal is defined by a perforated monogram motif, an evolution of the original Gucci rhombi design from the 1930s. Made in Italy.',
        'brand': 'Gucci',
        'category': 'Slides',
        'price': 399.99,
        'size': 11,
        'countInStock': 70,
        'rating': 4.9,
        'numReviews': 17,
    },
    {
        '_id': '13',
        'name': 'Air Jordan 3 SE "Canvas"',
        'image': '/images/air_jordan_three_se_canvas.jpg',
        'description':
        'As its moniker suggests, the latest take on Tinker Hatfield\'s first-ever design for Michael Jordan\'s signature sneaker line is constructed with durable canvas. A light beige "Muslin" color takes over most of the upper, while supporting components along the tongue, at the spine and around the lower heel opt for a deeper yellow that introduces an "aged" look.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 200.99,
        'countInStock': 10,
        'size': 12,
        'rating': 4.9,
        'numReviews': 30,
    },
    {
        '_id': '14',
        'name': 'Air Jordan 8 "Rui Hachimura"',
        'image': '/images/air_jordan_eight_rui_hachimura.jpg',
        'description':
        'A mix of perforated and non-perforated suede combines with smooth synthetic leather throughout the upper, with overlays across the profiles and along the tongue boasting an"age" pattern. Hachimura\'s logo replaces Jumpman branding on the top of the tongue, although chenille material reprises its role; both components opt for a bold scarlet tone that nods to a number of the forward\'s personal touch points. Elsewhere, the sneaker\'s packaging is reworked for the special occasion, with tissue paper donning the aforementioned logo alongside NIKE, Inc. branding. The box itself deviates from the standard graphics in favor of one that depicts Hachimura winning the ball from two spirit hoopers; Japanese characters accompanying the image of the Washington Wizard, depicted as wearing the special Jordan 8.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 225.99,
        'countInStock': 2,
        'size': 8,
        'rating': 3.9,
        'numReviews': 3,
    },
    {
        '_id': '15',
        'name': 'Air Jordan 3 SE "Canvas"',
        'image': '/images/air_jordan_three_se_canvas.jpg',
        'description':
        'As its moniker suggests, the latest take on Tinker Hatfield\'s first-ever design for Michael Jordan\'s signature sneaker line is constructed with durable canvas. A light beige "Muslin" color takes over most of the upper, while supporting components along the tongue, at the spine and around the lower heel opt for a deeper yellow that introduces an "aged" look.',
        'brand': 'Air Jordan',
        'category': 'Sneakers',
        'price': 200.99,
        'countInStock': 5,
        'size': 7,
        'rating': 4.1,
        'numReviews': 3,
    },
    {
        '_id': '16',
        'name': 'DIOR x Air Jordan 1 High',
        'image': '/images/dior_x_air_jordan_one_high.jpg',
        'description':
        'Jordan Brand connected with Parisian fashion house Dior to create history with the Jordan 1 Retro High Dior. This is the first time that Jordan has collaborated with a legacy fashion label like Dior, making this release one for the books. This release was limited to only 8,500 pairs, each pair individually numbered. This Jordan 1 Retro High is composed of a white and grey leather upper with traditional Dior monogram print Swoosh. These shoes are made in Italy with premium materials. Co-branded icy translucent soles, Dior branded tongue and Wings logo, and a silver "Air Dior" hang tag completes the design.',
        'brand': 'Dior',
        'category': 'Sneakers',
        'price': 7000.99,
        'size': 9,
        'countInStock': 1,
        'rating': 4.7,
        'numReviews': 3,
    },
]